- name: Copy settings 
  shell:
    cmd: cp -R ./dotfiles/.config ~/.config

- name: Linked .zshrc
  shell:
    cmd: cp -R ./dotfiles/shell/.zshrc ~/.zshrc

- name: Linked .tmux.conf
  shell:
    cmd: cp -R ./dotfiles/shell/.tmux.conf ~/.tmux.conf
