

- name: Linked .config 
  shell:
    cmd: ln -s ./dotfiles/.config ~/.config

- name: Linked .zshrc
  shell:
    cmd: ln -s ./dotfiles/shell/.zshrc ~/.zshrc

- name: Linked .tmux.conf
  shell:
    cmd: ln -s ./dotfiles/shell/.tmux.conf ~/.tmux.conf
