- name: Remove config
  shell:
    cmd: rm -rf ~/.config

- name: Remove oh-my-zsh
  shell:
    cmd: rm -rf ~/.oh-my-zsh

- name: Remove .zshrc
  shell:
    cmd: rm ~/.zshrc

- name: Remove .tmux.conf
  shell:
    cmd: rm ~/.tmux.conf

- name: Remove .tmux
  shell:
    cmd: rm ~/.tmux
